server:
  port: 443
  port-html : 80
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: vpfldk123!@#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-g66m6-kr.vpc-pub-cdb.ntruss.com:3306/bit4final?serverTimezone=Asia/Seoul
    username: study
    password: bit4!@#$
  servlet:
    multipart:
      max-file-size: 20MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  profiles:
    include: oauth
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
aws:
  s3:
    bucketName: bit701.bucket.102
jwt:
  secretKey: HellOImFakerIAgrreLGBTIlikeTeaMC0OKYoUKMowWhatImsaYinGIdONtKnowHAHeHaaaCutEMeaRonGGGG12312TQLVKFKasd
  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 72000000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루))
    header: Authorization-refresh
naver:
  login:
    client_id: qwQJi2mXut9egJr1uiFj
    client_secret: v3n11rGdRW
  translate:
    client_id: aaullc5zyk
    client_secret: Ad6GvUB4CSZS0ilyxUo9tUGWN7ZXQSBb8dp5gyf0
  sens:
    service_id: ncp:sms:kr:305197781446:devster-sms
    accessKey : tDdcJbDAJB2SiRYiC0vD
    secretKey : AxkRbXwgsDv4Dl5ypWleAdSSOLZ8SDFh8iLUQxtY
    number : "01044854249"
kakao:
  client_id: 168ba1a4e0e55db8af46e892ae6c7b82
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
    - /mapper/**/*.xml



