server:
  port: 443
  port-html : 80

  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: vpfldk123!@#

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-g66m6-kr.vpc-pub-cdb.ntruss.com:3306/bit4final?serverTimezone=Asia/Seoul
    username: study
    password: bit4!@#$
  servlet:
    multipart:
      max-file-size: 20MB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

aws:
  s3:
    bucketName: bit701.bucket.102